name: flet_flip_card
description: Flet FletFlipCard control
repository: https://github.com/MyGithubAccount/flet-flip-card/src/flutter/flet_flip_card
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-flip-card

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flip_card: ^0.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
